/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Carga;
import clases.Cliente;
import clases.Conductor;
import clases.Vehiculo;
import clases.Viaje;
import estructuras.estructura_BloqueC.Encriptar;
import estructuras.lista_enlazada_doble_circular;
import estructuras.lista_enlazada_doble_circular.nodo_doble;
import estructuras.lista_simple;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Alejandro Lorenty
 */
public class menu_Viajes extends javax.swing.JFrame {

    private int x;
    private int y;
    private DefaultComboBoxModel clienteBox = new DefaultComboBoxModel();
    private DefaultComboBoxModel conductorBox = new DefaultComboBoxModel();
    private DefaultComboBoxModel vehiculoBox = new DefaultComboBoxModel();
    private DefaultComboBoxModel origenBox = new DefaultComboBoxModel();
    private DefaultComboBoxModel destinoBox = new DefaultComboBoxModel();
    private lista_simple<Cliente> clientesTabla;
    private Viaje viajeUsuario;

    /**
     * Creates new form menu_Viajes
     */
    public menu_Viajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        MostrarField = new javax.swing.JTextField();
        MostradorPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ViajeArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        VehiculoArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConductorArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClienteArea = new javax.swing.JTextArea();
        Titulo = new javax.swing.JLabel();
        ImagenBoton = new javax.swing.JButton();
        grafico = new javax.swing.JButton();
        CrearViajeBoton = new javax.swing.JButton();
        DestinoLabel = new javax.swing.JLabel();
        DestinoBox = new javax.swing.JComboBox<>();
        OrigenLabel = new javax.swing.JLabel();
        OrigenBox = new javax.swing.JComboBox<>();
        Vehiculoslabel = new javax.swing.JLabel();
        VehiculosBox = new javax.swing.JComboBox<>();
        ConductoresLabel = new javax.swing.JLabel();
        ConductoresBox = new javax.swing.JComboBox<>();
        ClientesLabel = new javax.swing.JLabel();
        ClientesBox = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setLayout(null);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/logout72.png"))); // NOI18N
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jPanel1.add(Salir);
        Salir.setBounds(20, 500, 72, 72);

        MostrarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MostrarFieldKeyPressed(evt);
            }
        });
        jPanel1.add(MostrarField);
        MostrarField.setBounds(530, 540, 190, 24);

        MostradorPanel.setBackground(new java.awt.Color(0, 0, 0));
        MostradorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViajeArea.setEditable(false);
        ViajeArea.setBackground(new java.awt.Color(255, 102, 0));
        ViajeArea.setColumns(14);
        ViajeArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ViajeArea.setForeground(new java.awt.Color(255, 255, 255));
        ViajeArea.setRows(5);
        ViajeArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(ViajeArea);

        MostradorPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 260, 180));

        VehiculoArea.setEditable(false);
        VehiculoArea.setBackground(new java.awt.Color(255, 102, 0));
        VehiculoArea.setColumns(14);
        VehiculoArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        VehiculoArea.setForeground(new java.awt.Color(255, 255, 255));
        VehiculoArea.setRows(5);
        VehiculoArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(VehiculoArea);

        MostradorPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 180));

        ConductorArea.setEditable(false);
        ConductorArea.setBackground(new java.awt.Color(255, 102, 0));
        ConductorArea.setColumns(14);
        ConductorArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ConductorArea.setForeground(new java.awt.Color(255, 255, 255));
        ConductorArea.setRows(5);
        ConductorArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(ConductorArea);

        MostradorPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 260, 180));

        ClienteArea.setEditable(false);
        ClienteArea.setBackground(new java.awt.Color(255, 102, 0));
        ClienteArea.setColumns(14);
        ClienteArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ClienteArea.setForeground(new java.awt.Color(255, 255, 255));
        ClienteArea.setRows(5);
        ClienteArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(ClienteArea);

        MostradorPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 180));

        jPanel1.add(MostradorPanel);
        MostradorPanel.setBounds(380, 70, 570, 410);

        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("GESTION DE VIAJES");
        jPanel1.add(Titulo);
        Titulo.setBounds(540, 20, 240, 30);

        ImagenBoton.setBackground(new java.awt.Color(255, 255, 255));
        ImagenBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/imagen.png"))); // NOI18N
        ImagenBoton.setText("IMAGEN");
        ImagenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ImagenBoton);
        ImagenBoton.setBounds(320, 500, 190, 80);

        grafico.setBackground(new java.awt.Color(255, 255, 255));
        grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/graphviz.png"))); // NOI18N
        grafico.setText("GRAPHVIZ");
        grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoActionPerformed(evt);
            }
        });
        jPanel1.add(grafico);
        grafico.setBounds(110, 500, 200, 80);

        CrearViajeBoton.setBackground(new java.awt.Color(255, 255, 255));
        CrearViajeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/iviajes.png"))); // NOI18N
        CrearViajeBoton.setText("Crear Viaje");
        CrearViajeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearViajeBotonActionPerformed(evt);
            }
        });
        jPanel1.add(CrearViajeBoton);
        CrearViajeBoton.setBounds(740, 510, 190, 60);

        DestinoLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DestinoLabel.setForeground(new java.awt.Color(255, 255, 255));
        DestinoLabel.setText("DESTINO:");
        jPanel1.add(DestinoLabel);
        DestinoLabel.setBounds(20, 380, 180, 30);

        DestinoBox.setBackground(new java.awt.Color(0, 0, 0));
        DestinoBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinoBox.setForeground(new java.awt.Color(255, 255, 255));
        DestinoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(DestinoBox);
        DestinoBox.setBounds(20, 410, 290, 30);

        OrigenLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        OrigenLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrigenLabel.setText("ORIGEN:");
        jPanel1.add(OrigenLabel);
        OrigenLabel.setBounds(20, 300, 180, 30);

        OrigenBox.setBackground(new java.awt.Color(0, 0, 0));
        OrigenBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OrigenBox.setForeground(new java.awt.Color(255, 255, 255));
        OrigenBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(OrigenBox);
        OrigenBox.setBounds(20, 340, 290, 30);

        Vehiculoslabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Vehiculoslabel.setForeground(new java.awt.Color(255, 255, 255));
        Vehiculoslabel.setText("VEHICULO:");
        jPanel1.add(Vehiculoslabel);
        Vehiculoslabel.setBounds(20, 180, 180, 30);

        VehiculosBox.setBackground(new java.awt.Color(0, 0, 0));
        VehiculosBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VehiculosBox.setForeground(new java.awt.Color(255, 255, 255));
        VehiculosBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(VehiculosBox);
        VehiculosBox.setBounds(20, 220, 290, 30);

        ConductoresLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ConductoresLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConductoresLabel.setText("CONDUCTOR:");
        jPanel1.add(ConductoresLabel);
        ConductoresLabel.setBounds(20, 100, 180, 30);

        ConductoresBox.setBackground(new java.awt.Color(0, 0, 0));
        ConductoresBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ConductoresBox.setForeground(new java.awt.Color(255, 255, 255));
        ConductoresBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ConductoresBox);
        ConductoresBox.setBounds(20, 140, 290, 30);

        ClientesLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ClientesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClientesLabel.setText("CLIENTE:");
        jPanel1.add(ClientesLabel);
        ClientesLabel.setBounds(20, 20, 180, 30);

        ClientesBox.setBackground(new java.awt.Color(0, 0, 0));
        ClientesBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ClientesBox.setForeground(new java.awt.Color(255, 255, 255));
        ClientesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ClientesBox);
        ClientesBox.setBounds(20, 60, 290, 30);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/viajes.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 1080, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void llenarComboBox() throws Exception {
        ClientesBox.setModel(clienteBox);
        clienteBox.addElement("Seleccione Un Cliente");
        Cliente c1;

        ConductoresBox.setModel(conductorBox);
        conductorBox.addElement("Seleccione Un Conductor");
        Conductor c2;

        VehiculosBox.setModel(vehiculoBox);
        vehiculoBox.addElement("Seleccione Un Vehiculo");
        Vehiculo v;

        OrigenBox.setModel(origenBox);
        origenBox.addElement("Seleccione su punto de Origen");
        DestinoBox.setModel(destinoBox);
        destinoBox.addElement("Seleccione su punto de Destino");

        if (Carga.clientes.getTabla_H() != null) {
            for (int i = 0; i < Carga.clientes.getCapacidad(); i++) {
                clientesTabla = Carga.clientes.devolver_nodo(i);
                if (clientesTabla != null) {
                    for (int j = 0; j < clientesTabla.size(); j++) {
                        c1 = clientesTabla.get(j);
                        clienteBox.addElement(c1.getDPI());
                    }
                }

            }
        }

        if (Carga.conductores.tamanioLista() != 0) {
            for (int i = 1; i < Carga.conductores.tamanioLista() + 1; i++) {
                c2 = Carga.conductores.retornarNodobyIndex(i);
                conductorBox.addElement(c2.getDPI());
            }
        }

        if (Carga.vehiculos.sizeElementosArbol() != 0) {
            lista_simple<Vehiculo> elementos_arbol = Carga.vehiculos.arrayVehiculos();
            for (int i = 0; i < elementos_arbol.size(); i++) {
                v = (Vehiculo) elementos_arbol.get(i);
                vehiculoBox.addElement(v.getPlaca());
            }
        }

        if (Carga.grafo.getSize() != 0) {

            for (int i = 0; i < Carga.grafo.getSize(); i++) {

                origenBox.addElement(Carga.grafo.getRuta(i));
                destinoBox.addElement(Carga.grafo.getRuta(i));
            }
        }
    }
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_SalirMouseClicked

    public long valorAssci(String subCadena) {

        long result = 0;
        String str = null;
        str = subCadena;
        StringBuilder sb = new StringBuilder();
        for (char c : str.toCharArray()) {
            sb.append((int) c);
        }
        result = Long.parseLong(sb.toString());
        return result;
    }
    private void CrearViajeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearViajeBotonActionPerformed

        if (CrearViajeBoton.getText().equals("Crear Viaje")) {

            if (!ClientesBox.getSelectedItem().equals("Seleccione Un Cliente")
                    && !ConductoresBox.getSelectedItem().equals("Seleccione Un Conductor")
                    && !VehiculosBox.getSelectedItem().equals("Seleccione Un Vehiculo")
                    && !OrigenBox.getSelectedItem().equals("Seleccione su punto de Origen")
                    && !DestinoBox.getSelectedItem().equals("Seleccione su punto de Destino")
                    && !OrigenBox.getSelectedItem().equals(DestinoBox.getSelectedItem())) {
                viajeUsuario = new Viaje();
                long dpi = Long.parseLong(String.valueOf(ClientesBox.getSelectedItem()));
                Cliente eC = null;
                clientesTabla = Carga.clientes.devolver_nodo(dpi);
                for (int i = 0; i < clientesTabla.size(); i++) {
                    try {
                        if (clientesTabla.get(i).getDPI() == dpi) {
                            eC = clientesTabla.get(i);
                            break;
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(menu_Cliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                ClienteArea.setText("CLIENTE QUE SOLICITA EL VIAJE:" + "\n" + "\n"
                        + "DPI: " + String.valueOf(eC.getDPI()) + "\n"
                        + "NOMBRES: " + eC.getNombres() + "\n"
                        + "APELLIDOS: " + eC.getApellidos() + "\n"
                        + "TELEFONO: " + String.valueOf(eC.getTelefono()) + "\n"
                        + "GENERO: " + eC.getGenero() + "\n"
                        + "FECHA DE NACIMIENTO: " + eC.getFecha_nac());

                long dpiC = Long.parseLong(String.valueOf(ConductoresBox.getSelectedItem()));
                Conductor eC2;
                eC2 = Carga.conductores.retornarDato(dpiC);

                ConductorArea.setText("CONDUCTOR QUE REALIZARA EL VIAJE:" + "\n" + "\n"
                        + "DPI: " + String.valueOf(eC2.getDPI()) + "\n"
                        + "NOMBRES: " + eC2.getNombres() + "\n"
                        + "APELLIDOS: " + eC2.getApellidos() + "\n"
                        + "TELEFONO: " + String.valueOf(eC2.getTelefono()) + "\n"
                        + "TIPO DE LICENCIA: " + String.valueOf(eC2.getLicencia()) + "\n"
                        + "GENERO: " + eC2.getGenero() + "\n"
                        + "FECHA DE NACIMIENTO: " + eC2.getFecha_nac());
                long placaNo = valorAssci(String.valueOf(VehiculosBox.getSelectedItem()));
                Vehiculo eC3 = null;
                try {

                    eC3 = Carga.vehiculos.obtenerVehiculo(placaNo);

                    VehiculoArea.setText("VEHICULO ESCOGIDO PARA EL VIAJE" + "\n" + "\n"
                            + "PLACA: " + eC3.getPlaca() + "\n"
                            + "MARCA: " + eC3.getMarca() + "\n"
                            + "AÑO: " + String.valueOf(eC3.getAnio()) + "\n"
                            + "PRECIO: " + String.valueOf(eC3.getPrecio()) + "\n"
                            + "MODELO: " + eC3.getModelo() + "\n"
                            + "COLOR: " + eC3.getColor() + "\n"
                            + "TRANSMISION: " + eC3.getTransmision() + "\n");
                } catch (Exception ex) {
                    Logger.getLogger(menu_Viajes.class.getName()).log(Level.SEVERE, null, ex);
                }

                ViajeArea.setText("VIAJE A REALIZAR:" + "\n" + "\n"
                        + "LUGAR ORIGEN: " + OrigenBox.getSelectedItem().toString() + "\n"
                        + "LUGAR DESTINO: " + DestinoBox.getSelectedItem().toString());
                try {
                    viajeUsuario = Carga.grafo.metCorto(OrigenBox.getSelectedItem().toString(), DestinoBox.getSelectedItem().toString());
                } catch (Exception ex) {
                    Logger.getLogger(menu_Viajes.class.getName()).log(Level.SEVERE, null, ex);
                }
                viajeUsuario.getCliente().agregarNodo(eC, eC.getDPI());
                viajeUsuario.getConductor().agregarNodo(eC2, eC2.getDPI());
                viajeUsuario.getVehiculo().agregarNodo(eC3, eC3.getPlaca());
                CrearViajeBoton.setText("Confirmar Viaje");
                viajeUsuario.setClave(eC3.getPlaca());
                System.out.println(viajeUsuario.getClave());
                viajeUsuario.setFecha();
                System.out.println(viajeUsuario.getFecha());

            }

        } else if (CrearViajeBoton.getText().equals("Confirmar Viaje")) {
            try {
                Carga.viajes.nuevoBloque(viajeUsuario, Encriptar.MD5Code(viajeUsuario.getClave()), viajeUsuario.getFecha());
                System.out.println(Encriptar.MD5Code(viajeUsuario.getClave()));
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(menu_Viajes.class.getName()).log(Level.SEVERE, null, ex);
            }
            viajeUsuario.getViaje().imprimir();
            ClienteArea.setText("");
            ConductorArea.setText("");
            VehiculoArea.setText("");
            ViajeArea.setText("");

            for (Component component : jPanel1.getComponents()) {
                if (component instanceof JComboBox) {
                    ((JComboBox) component).setSelectedIndex(0);
                }
            }
            CrearViajeBoton.setText("Crear Viaje");
        } else if (CrearViajeBoton.getText().equals("Limpiar")) {
            for (Component component : jPanel1.getComponents()) {
                if (component instanceof JComboBox) {
                    ((JComboBox) component).setSelectedIndex(0);
                }
                ClienteArea.setText("");
                ConductorArea.setText("");
                VehiculoArea.setText("");
                ViajeArea.setText("");
                CrearViajeBoton.setText("Crear Viaje");
            }
        }
    }//GEN-LAST:event_CrearViajeBotonActionPerformed

    private void graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoActionPerformed
        //MÉTODO PARA CREAR EL ARCHIVO.DOT Y LA IMAGEN.PNG
        try {
            Path CMD = Carga.block_chain_GRAPHVIZ();
            Carga.dibujarGRAPHVIZ(CMD, "Viajes.png");
        } catch (IOException ex) {
            Logger.getLogger(carga_Masiva.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(menu_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_graficoActionPerformed

    private void ImagenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenBotonActionPerformed
        File miGraphviz = new File("Viajes.png");
        try {
            Desktop.getDesktop().open(miGraphviz);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "IMAGEN CARGANDO");
        }
        mostrador_imagen imagen = new mostrador_imagen();
        ImageIcon foto = new ImageIcon("./Viajes.png");
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(imagen.GraphvizLabel.getWidth(), imagen.GraphvizLabel.getHeight(), Image.SCALE_DEFAULT));
        imagen.GraphvizLabel.setIcon(icono);
        imagen.setVisible(true);
    }//GEN-LAST:event_ImagenBotonActionPerformed

    private void MostrarFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MostrarFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!MostrarField.getText().equals("")) {
                Viaje mostrar = null;
                try {
                    System.out.println(Encriptar.MD5Code(MostrarField.getText()));
                    mostrar = Carga.viajes.buscarTransaccion(Encriptar.MD5Code(MostrarField.getText()));
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(menu_Viajes.class.getName()).log(Level.SEVERE, null, ex);
                }
                Cliente eC = mostrar.getCliente().retornarNodobyIndex(0);
                Conductor eC2 = mostrar.getConductor().retornarNodobyIndex(0);
                Vehiculo eC3 = mostrar.getVehiculo().retornarNodobyIndex(0);
                lista_simple<String> viajeXD = mostrar.getViaje();
                ClienteArea.setText("CLIENTE QUE SOLICITA EL VIAJE:" + "\n" + "\n"
                        + "DPI: " + String.valueOf(eC.getDPI()) + "\n"
                        + "NOMBRES: " + eC.getNombres() + "\n"
                        + "APELLIDOS: " + eC.getApellidos() + "\n"
                        + "TELEFONO: " + String.valueOf(eC.getTelefono()) + "\n"
                        + "GENERO: " + eC.getGenero() + "\n"
                        + "FECHA DE NACIMIENTO: " + eC.getFecha_nac());

                ConductorArea.setText("CONDUCTOR QUE REALIZARA EL VIAJE:" + "\n" + "\n"
                        + "DPI: " + String.valueOf(eC2.getDPI()) + "\n"
                        + "NOMBRES: " + eC2.getNombres() + "\n"
                        + "APELLIDOS: " + eC2.getApellidos() + "\n"
                        + "TELEFONO: " + String.valueOf(eC2.getTelefono()) + "\n"
                        + "TIPO DE LICENCIA: " + String.valueOf(eC2.getLicencia()) + "\n"
                        + "GENERO: " + eC2.getGenero() + "\n"
                        + "FECHA DE NACIMIENTO: " + eC2.getFecha_nac());

                VehiculoArea.setText("VEHICULO ESCOGIDO PARA EL VIAJE" + "\n" + "\n"
                        + "PLACA: " + eC3.getPlaca() + "\n"
                        + "MARCA: " + eC3.getMarca() + "\n"
                        + "AÑO: " + String.valueOf(eC3.getAnio()) + "\n"
                        + "PRECIO: " + String.valueOf(eC3.getPrecio()) + "\n"
                        + "MODELO: " + eC3.getModelo() + "\n"
                        + "COLOR: " + eC3.getColor() + "\n"
                        + "TRANSMISION: " + eC3.getTransmision() + "\n");
                ViajeArea.setText("VIAJE REALIZADO" + "\n");
                for (int i = 0; i < viajeXD.getSize(); i++) {
                    ViajeArea.setText(ViajeArea.getText() + viajeXD.get(i) + "\n");
                }
                CrearViajeBoton.setText("Limpiar");
            }
        }
    }//GEN-LAST:event_MostrarFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_Viajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ClienteArea;
    private javax.swing.JComboBox<String> ClientesBox;
    private javax.swing.JLabel ClientesLabel;
    private javax.swing.JTextArea ConductorArea;
    private javax.swing.JComboBox<String> ConductoresBox;
    private javax.swing.JLabel ConductoresLabel;
    private javax.swing.JButton CrearViajeBoton;
    private javax.swing.JComboBox<String> DestinoBox;
    private javax.swing.JLabel DestinoLabel;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton ImagenBoton;
    private javax.swing.JPanel MostradorPanel;
    private javax.swing.JTextField MostrarField;
    private javax.swing.JComboBox<String> OrigenBox;
    private javax.swing.JLabel OrigenLabel;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextArea VehiculoArea;
    private javax.swing.JComboBox<String> VehiculosBox;
    private javax.swing.JLabel Vehiculoslabel;
    private javax.swing.JTextArea ViajeArea;
    private javax.swing.JButton grafico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
